sections:
  general:
    display: General
    fields:
      -
        handle: section_general
        field:
          type: section
          listable: hidden
          display: 'General configuration'
          instructions: 'Global site configuration options.'
      -
        handle: logo_lg
        field:
          mode: grid
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Logo:Desktop'
          type: assets
          icon: assets
          listable: hidden
          width: 50
      -
        handle: logo_sm
        field:
          mode: grid
          container: assets
          folder: /
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Logo:Mobile'
          type: assets
          icon: assets
          listable: hidden
          width: 50
  error_messages:
    display: 'Error messages'
    fields:
      -
        handle: section_404
        field:
          type: section
          listable: hidden
          display: '404 error'
      -
        import: error_message
        prefix: '404_'
